config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'leads#index'
  resource :leads
  resource :customers

  get '/dashboard', to: 'application#dashboard'
  post '/leads/update/status', to: 'leads#update_status_complete', as: 'lead_update_status'
  post '/lead_generation', to: 'leads#lead_generation'
  get '/leads/generate', to: 'application#export', as: 'lead_generate_csv'
  get '/leads/generate_lead_data', to: 'application#export_lead_data'
  get '/website_leads', to: 'leads#website_leads', as: 'website_leads'
  post '/update/assigned_to', to: 'leads#update_assigned_to', as: 'update_assigned_to'
  get 'search/tickets', to: 'leads#find'
  post 'search/tickets', to: 'leads#find_filter'
  get 'customers/index', to: 'customers#index'
  get 'customers/fetch', to: 'customers#fetch_customer'
  delete 'customers/delete', to: 'customers#destroy', as: 'customers_destroy'
  post 'customers/merge', to: 'customers#merge_customers'
  get '/customers/generate_customer_items_data', to: 'customers#export_customer_order_data'
  get '/work/index', to: 'application#work_index'
  post 'customers/called', to: 'customers#called'

  # authentication
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'
end

app/models/lead.rb
require 'csv'

class Lead < ApplicationRecord
    belongs_to :customer
	belongs_to :employee
	has_many :activities, dependent: :delete_all
	has_rich_text :description

    enum status: {
		just_in: 0,
        designing: 1,
		printing: 2,
		development: 3,
		binding: 4,
		post_press: 5,
		ready_for_delivery: 6,
		payment_pending: 7,
		completed: 8
	}

	scope :soul_less, -> { joins(:employee).where('employees.name ILIKE ?','LEAD MASTER') }

	scope :last_month, lambda {
        previous_month_begin = (Time.now - 1.month).beginning_of_month
        previous_month_end = (Time.now - 1.month).end_of_month
        where('created_at BETWEEN ? and ?',previous_month_begin,previous_month_end)
    }

	scope :for_month, -> (specific_month) {
        month_begin = (Date.parse(specific_month)).beginning_of_month
        month_end = (Date.parse(specific_month)).end_of_month
        where('created_at BETWEEN ? and ?',month_begin,month_end)
    }

	after_create :set_activities
	after_update :set_activities_for_status

	def self.item_type_list
		[
			"visiting_card",
			"poster",
			"webs_design_&_development",
			"digital_marketing",
			"design",
			"catalogue",
			"envelope",
			"letterpad",
			"letterhead",
			"bill_book",
			"brochure",
			"id_card",
			"sticker",
			"binding",
			"banner/flex",
			"standee",
			"vinyl_stickers",
			"receipt_books",
			"certificate",
			"admission_form",
			"label",
			"pamphlet",
			"invitation",
			"diary",
			"box",
			"notepads",
			"tag",
			"folder",
			"invoice_book",
			"file",
			"inserts",
			"leaflet",
			"hardcase_books",
			"softcover_books",
			"annual_report",
			"calendar",
			"Inlay cards",
			"Booklet souvenir",
			"magazine",
			"Examination card",
			"office stationery",
			"Coupon",
			"bag",
			"Standy",
			"Slip pad",
			"Order form",
			"register",
			"books",
			"ticket",
			"voucher_pad",
			"registration_form",
			"chit_cards",
			"pass_book",
			"others"
		]
	end

	def self.to_csv
		attributes = %w{id customer_info items info}
		
		CSV.generate(headers: true) do |csv|
			csv << attributes
	
			all.find_each do |user|
			csv << attributes.map{ |attr| user.send(attr) }
			end
		end
	end

	def creator
		Employee.find_by(id: self.created_by)
	end

	def created_date
        "#{created_at.in_time_zone("Chennai").strftime("%d %b, %l:%M %p")}"
    end

	def info
		"#{description.to_plain_text}"
	end

	def customer_info
		"#{customer.name} #{customer.company_name} #{customer.mobile} #{customer.email}"
	end

	def items
		JSON.parse(item_type).reject(&:blank?).join(",") rescue ""
	end

	def set_activities
		description = "Order created"
		lead_id = self.id
		Activity.create_new(description,lead_id)
	end

	def set_activities_for_status
		if self.saved_changes["status"].present?
			description = "Status updated from #{self.saved_changes["status"][0]} to #{self.saved_changes["status"][1]}"
			lead_id = self.id
			Activity.create_new(description,lead_id)
		end
	end

	def display_name
		"RP#{self.id.to_s.rjust(6,'0')}" rescue "RP(undefined)"
	end
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
    skip_before_action :verify_authenticity_token, only: [:lead_generation]
    skip_before_action :require_login, only: [:lead_generation]

    def index
        piyush_logic_status = ((params["filter"] && params["filter"]["filter_by_status"].present?) || params["query"].present?) ? 
            ["completed"] : ["completed","payment_pending","ready_for_delivery"]
        @leads = Lead.order(created_at: :desc).where.not(status: piyush_logic_status)   
        if params["filter"].present?
            begin
                employee_name = params["filter"]["assigned_to"] rescue false
                lead_status = params["filter"]["filter_by_status"] rescue false
                priority = params["filter"]["priority"] rescue false
                filtered_date = params["filter"]["by_date"] rescue false
                if employee_name.present?
                    employee = (employee_name == "me") ? Employee.find_by(id: @current_employee.id) : Employee.where('lower(name) = ?',employee_name).first
                    @leads = @leads.where(employee_id: employee.id)
                end
                if lead_status.present?
                    @leads = @leads.where(status: lead_status)
                end
                if priority.present?
                    @leads
                end
                if filtered_date.present?
                    @leads = @leads.where(created_at: filtered_date.to_date.beginning_of_day..filtered_date.to_date.end_of_day)
                end
            rescue
            end
        end

        if params["query"].present?
            @leads = @leads.joins(:customer).where("customers.name ILIKE ? OR customers.company_name ILIKE ? OR item_type ILIKE ? OR CAST(leads.id as VARCHAR) ILIKE ?","%#{params["query"]}%","%#{params["query"]}%","%#{params["query"]}%","%#{params["query"]}")
            @leads = search_using_display_name(params["query"]) if params["query"].include?("RP")
        end
        computer_employee = Employee.find_by(employee_type: "computer").id
        @leads = @leads.where.not(employee_id: computer_employee)
        @leads_count = @leads.count
    end

    def new
        @lead = Lead.new
    end

    def edit
        @lead = Lead.find_by(id: params[:id])
    end

    def show
        @lead = Lead.find_by(id: params[:id])
    end

    def create
        @lead = Lead.new(lead_params)
        if @lead.save
            redirect_to leads_path(id: @lead)
        else
            render "new"
        end
    end

    def update
        @lead = Lead.find_by(id: params[:id])
        if @lead.update(lead_params)
            redirect_to leads_path(id: @lead)
        else
            render "edit"
        end
    end

    def update_assigned_to
        @lead = Lead.find_by(id: params[:id]) rescue nil
        updated_assigned_to_id = params[:employee_id]
        @lead.update(employee_id: updated_assigned_to_id)
        redirect_to leads_path(id: @lead)
    end

    def destroy
        @lead = Lead.find_by(id: params[:id])
        @lead.destroy
        redirect_to root_path
    end

    def update_status_complete
        @lead = Lead.find_by(id: params[:id])
        if params[:status].present? and Lead.statuses.include?(params[:status])
            @lead.update(status: params[:status])
        end
        if params[:status] == "completed"
            root_params = params[:root_params].to_unsafe_h.except(:action, :controller)
            redirect_to root_path(root_params)
        else
            render json: {success: "Lead successfully updated"}
        end
    end

    def lead_generation
        @customer = Customer.find_or_create_by(customer_api_params)
        if @customer.save
            @employee = Employee.find_by(employee_type: "computer", name: "Automation")
            @lead = Lead.new(customer_id: @customer.id, description: htmlIZE(params[:description]), employee_id: @employee.id, created_by: @employee.id, status: 'just_in')
            if @lead.save
                LeadMailer.with(customer: @customer).confirmation_mail.deliver_now
                render json: {success: "Lead successfully created"}
            else
                render json: {error: "Lead creation issue"}
            end
        else
            render json: {error: "Customer creation issue"}
        end
    end

    def website_leads
        employee_id = Employee.find_by(employee_type: "computer").id
        @leads = Lead.order(created_at: :desc).where(employee_id: employee_id)
        @leads_count = @leads.count
        render 'index'
    end

    def find
        @leads = []
    end

    def find_filter
        customer_id = params[:customer_id]
        leads_display_number = params[:lead_id]
        search_term = params[:search]
        @leads = []
        if customer_id.present?
            selected_customer = Customer.find_by(id: customer_id)
            @leads = selected_customer.leads
        end
        if leads_display_number.present?
            @leads = search_using_display_name(leads_display_number) if leads_display_number.include?("RP")
            @leads = Lead.where(status: "completed").joins(:customer).where("customers.name ILIKE ? OR customers.company_name ILIKE ? OR item_type ILIKE ? OR CAST(leads.id as VARCHAR) ILIKE ?","%#{leads_display_number}%","%#{leads_display_number}%","%#{leads_display_number}%","%#{leads_display_number}") unless leads_display_number.include?("RP")
        end
        if search_term.present?
            @leads = Lead.where(status: "completed").joins(:customer).where("customers.name ILIKE ? OR customers.company_name ILIKE ? OR item_type ILIKE ? OR CAST(leads.id as VARCHAR) ILIKE ?","%#{search_term}%","%#{search_term}%","%#{search_term}%","%#{search_term}")
        end
        unless @leads.present?
            flash[:error] = "No records available"
        end
        flash[:error] = "No records available"
        render 'find'
    end

    private
        def htmlIZE(str)
            "<div>"+str+"</div>"
        end

        def customer_api_params
            params.permit(:description)
            params.permit(:name,:mobile,:email)
        end

        def lead_params
            params.require(:lead).permit(:customer_id, :employee_id, :created_by, :description, :quantity, :paper_type, :colour, :s_no, :slip_no, :size, :payment_details, :status, :item_type => [])
        end

        def search_using_display_name(str)
            id = str[2..-1].to_i
            Lead.where(id: id)
        end
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/views/leads/_completed_leads.html.erb
<% leads.each do |lead| %>
    <a href="<%= leads_path(id: lead) %>">
        <div class="lead-tile">
            <div class="info" style="border: 5px solid #198754">
                <div class="alignment-completed">
                    <div>
                        <span><%= lead.display_name %></span>
                        <div class="lead-h3"><%= item_type_csv(lead) %></div>
                        <div class="flexer">
                            <div class="padding-right-1">
                                <div class="lead-dull">Created By</div>
                                <div class="lead-text"><%= get_creater(lead.created_by) rescue '-' %></div>
                            </div>
                            <div class="padding-right-1">
                                <div class="lead-dull">Created At</div>
                                <div class="lead-text"><%= standard_datetime(lead.created_at) rescue '-' %></div>
                            </div>
                        </div>
                    </div>
                    <div class="right-align">
                        <div class="lead-h3"><%= lead.customer.company_name == "" ? 'Not available' : lead.customer.company_name rescue 'Not available' %></div>
                        <div class="flexer-right">
                            <div class="padding-left-1">
                                <div class="lead-dull">Customer name</div>
                                <div class="lead-text"><%= lead.customer.name == "" ? "-" : lead.customer.name rescue '-' %></div>
                            </div>
                            <div class="padding-left-1">
                                <div class="lead-dull">Contact info</div>
                                <div class="lead-text"><%= lead.customer.mobile.present? ? lead.customer.mobile : '-' rescue '-' %></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </a>
<% end %>

app/views/leads/_form.html.erb
<div class="lead-form">
<div class="back-button">
    <a href="<%= @lead.present? and @lead.id.present? ? leads_path(id: @lead) : root_path rescue 'root_path' %>">
        <i><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-left" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z"/>
        </svg>
        Back</i>
    </a>
</div>
<%= form_with model: @lead, url: leads_path(id: @lead) do |form| %>
    <div class="row">
        <div class="col-lg-6">
            <div class='lead-form-input' style="margin-bottom: 20px;">
                <div class="flexer">
                    <div class="margin-right-auto">Customer</div>
                    <div class="padding-left-1 text-primary add-new-position" data-bs-toggle="modal" data-bs-target="#customerFormModal">
                        Add New
                    </div>
                </div>
                <%= form.select :customer_id, customer_select, {}, {id: 'customer_select_2', class: 'form-control lead-form-input-style', required: true} %>
            </div>

            <div class='lead-form-input'>
                <div class="flexer">
                    <div class="margin-right-auto">Items</div>
                    <div class="padding-left-1 text-primary add-new-position" data-bs-toggle="modal" data-bs-target="#itemFormModal">
                        Add New
                    </div>
                </div>
                <%= form.select :item_type, options_for_select(item_select_options(@lead),item_select_value(@lead)), {}, {id: 'item_select_2',class: 'form-control lead-form-input-style', multiple: true, required: true   } %>
            </div>

            <div class='lead-form-input'>
                <%= form.label :quantity, "Quantity" %>
                <%= form.text_area :quantity, class: 'form-control lead-form-input-style' %>
            </div>

            <%= hidden_field_tag :"lead[created_by]", current_employee_id %>
        </div>
        <div class="col-lg-6">
            <div class='lead-form-input'>
                <%= form.label :employee, "Assign To" %>
                <%= form.select :employee_id, employee_select, {}, {class: 'form-control lead-form-input-style'} %>
            </div>

            <div class='lead-form-input'>
                <%= form.label :status, "Status" %>
                <%= form.select :status, status_select_just_in, {}, {class: 'form-control lead-form-input-style'} %>
            </div>
        </div>
        <div class=''>
                <%= form.label :description, "Description" %>
                <%= form.rich_text_area :description, class: 'form-control ', input_html: { rows: 10 } %>
            </div>
    </div>

    

    <div class='lead-form-input' style="text-align: right;padding-top: 20px;">
        <span class="btn btn-warning"><a href="<%= root_path %>">Cancel</a></span>
        <%= form.submit "Submit", class: 'btn btn-success' %>
    </div>

<% end %>

<div class="modal fade" id="customerFormModal" tabindex="-1" aria-labelledby="customerForm" aria-hidden="true">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="customerFormModalLabel">New Customer</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <%= render 'customers/form', customer: new_customer, popup: true %>
        </div>
        <div class="modal-footer">
            <span class="edit-button cursor-pointer" id="customer-close" data-bs-dismiss="modal">Close</span>
            <button type="button" class="btn btn-warning" id="popup-customer-submit">Save</button>
        </div>
        </div>
    </div>
</div>

<div class="modal fade" id="itemFormModal" tabindex="-1" aria-labelledby="itemForm" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="customerFormModalLabel">New Item</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <input type="text" name="new_item" id="new_item_string" placeholder="New Item" class="form-control">
        </div>
        <div class="modal-footer">
            <span class="btn btn-warning cursor-pointer" id="item-close" data-bs-dismiss="modal">Close</span>
            <button type="button" class="btn btn-success" id="popup-new-item-submit">Save</button>
        </div>
        </div>
    </div>
</div>

</div>

app/views/leads/_leads.html.erb
<% leads.each do |lead| %>
    <a href="<%= leads_path(id: lead) %>">
        <div class="lead-tile">
            <div class="info">
                <div class="alignment">
                    <div>
                        <span><%= lead.display_name %></span>
                        <div class="lead-h3"><%= item_type_csv(lead) %></div>
                        <div class="flexer">
                            <div class="padding-right-1">
                                <div class="lead-dull">Created By</div>
                                <div class="lead-text"><%= get_creater(lead.created_by) rescue '-' %></div>
                            </div>
                            <div class="padding-right-1">
                                <div class="lead-dull">Assigned To</div>
                                <div class="lead-text"><%= lead.employee.name rescue '-' %></div>
                            </div>
                            <div class="padding-right-1">
                                <div class="lead-dull">Created At</div>
                                <div class="lead-text"><%= standard_datetime(lead.created_at) rescue '-' %></div>
                            </div>
                        </div>
                    </div>
                    <div class="right-align">
                        <div class="lead-h3"><%= lead.customer.company_name == "" ? 'Not available' : lead.customer.company_name rescue 'Not available' %></div>
                        <div class="flexer-right">
                            <div class="padding-left-1">
                                <div class="lead-dull">Customer name</div>
                                <div class="lead-text"><%= lead.customer.name == "" ? "-" : lead.customer.name rescue '-' %></div>
                            </div>
                            <div class="padding-left-1">
                                <div class="lead-dull">Contact info</div>
                                <div class="lead-text"><%= lead.customer.mobile.present? ? lead.customer.mobile : '-' rescue '-' %></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="status <%= status_background(lead) %>">
                    <div class="lead-h3">Status</div>
                    <div class="lead-text"><%= capitalize(lead.status) %></div>
                </div>
            </div>
        </div>
    </a>
    
    <% if lead.status == 'ready_for_delivery' or lead.status == 'payment_pending' %>
    <div class="completed-short-cut">
        <span>
            <%= link_to lead_update_status_path(id: lead,status: 'completed',root_params: params.to_unsafe_h), method: 'POST', :data => {:confirm => 'Are you sure?'} do %>
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-check2-square" viewBox="0 0 16 16">
                    <path d="M3 14.5A1.5 1.5 0 0 1 1.5 13V3A1.5 1.5 0 0 1 3 1.5h8a.5.5 0 0 1 0 1H3a.5.5 0 0 0-.5.5v10a.5.5 0 0 0 .5.5h10a.5.5 0 0 0 .5-.5V8a.5.5 0 0 1 1 0v5a1.5 1.5 0 0 1-1.5 1.5H3z"/>
                    <path d="m8.354 10.354 7-7a.5.5 0 0 0-.708-.708L8 9.293 5.354 6.646a.5.5 0 1 0-.708.708l3 3a.5.5 0 0 0 .708 0z"/>
                </svg>
                Completed
            <% end %>
        </span>
    </div>
    <% end %>
<% end %>

app/views/leads/_show_actions.html.erb
<div class="lead-buttons">
    <div class="ticket-actions" style="margin-top: 0px;">
        <div class="lead-h3">Update Status</div>
        <div class="lead-status-style" data-current_lead="<%= @lead.status %>">
            <%= select_tag "status", options_for_select(status_options,current_status(@lead)), class: 'form-control', id: 'show-status-update' %>
            <div class="status-icons-div">
            <span class="bootstrap-close-icon">
                &times;
            </span>
            <span class="bootstrap-check-icon">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-check" viewBox="0 0 16 16">
                    <path d="M10.97 4.97a.75.75 0 0 1 1.07 1.05l-3.99 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.267.267 0 0 1 .02-.022z"/>
                </svg>
            </span>
            </div>
        </div>
        <div class="lead-h3">Assign Ticket</div>
        <form action="<%= update_assigned_to_path(id: @lead.id) %>" method="post">
            <div class="assign_to-style">
                <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
                <%= select_tag "employee_id", options_for_select(employee_select(true),@lead&.employee&.id), class: 'form-control', id: 'assigned-to-update' %>
                <div class="assigned-to-icons-div">
                    <span class="bootstrap-close-icon assigned-to-close-icon">
                        &times;
                    </span>
                    <button class="bootstrap-check-icon" style="border: none;" type="submit">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-check" viewBox="0 0 16 16">
                            <path d="M10.97 4.97a.75.75 0 0 1 1.07 1.05l-3.99 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.267.267 0 0 1 .02-.022z"/>
                        </svg>
                    </button>
                </div>
            </div>
        </form>
        <div class="lead-h3">Ticket Actions</div>
        <div class="button-div">
            <div class="edit-button"><a href="<%= edit_customers_path(id: @lead.customer.id) %>">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                    <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                    <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                </svg>
                Edit Customer Info
            </a></div>
            <div class="edit-button"><a href="<%= edit_leads_path(id: @lead) %>">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                    <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                    <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                </svg>
                Edit Order Info</a>
            </div>
        </div>
        <div class="ticket-action-green">
            <%= link_to lead_update_status_path(id: @lead,status: 'completed'), method: 'POST', :data => {:confirm => 'Are you sure?'} do %>
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-check2-square" viewBox="0 0 16 16">
                <path d="M3 14.5A1.5 1.5 0 0 1 1.5 13V3A1.5 1.5 0 0 1 3 1.5h8a.5.5 0 0 1 0 1H3a.5.5 0 0 0-.5.5v10a.5.5 0 0 0 .5.5h10a.5.5 0 0 0 .5-.5V8a.5.5 0 0 1 1 0v5a1.5 1.5 0 0 1-1.5 1.5H3z"/>
                <path d="m8.354 10.354 7-7a.5.5 0 0 0-.708-.708L8 9.293 5.354 6.646a.5.5 0 1 0-.708.708l3 3a.5.5 0 0 0 .708 0z"/>
                </svg>
                Completed
            <% end %>
        </div>
        <div class="delete-button"><a href="<%= leads_path(id: @lead) %>" data-method="delete" data-confirm="Are you sure ?">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3-fill" viewBox="0 0 16 16">
                <path d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5Zm-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5ZM4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06Zm6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528ZM8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5Z"/>
            </svg>
            Delete
            </a>
        </div>
    </div>
</div>

app/views/leads/edit.html.erb
<%= render "leads/form", lead: @lead %>

app/views/leads/find.html.erb
<div class="index-leads">
    <h4>Apply filters</h4>
    <div class="flexer-space-between">        
        <div>
            <%= form_with url: '/search/tickets' do |f| %>
                <%= f.select :customer_id, customer_select, {}, {id: 'customer_select_2_2', class: ''} %>&nbsp;OR&nbsp;
                <input type="text" placeholder="RPXXXXXX" name="lead_id" class="form-control-custom small-input-box">&nbsp;OR&nbsp;
                <input type="text" placeholder="Search Key" name="search" class="form-control-custom small-input-box">
                <button type="submit" class="btn-warning form-control-custom">Apply</button>
            <% end %>
        </div>
        <div class="lead-dull">
            <%= @leads.count %> tickets displayed
        </div>
    </div>
    <div class="">
        <div class="record-tile">
            <%= render "leads/completed_leads", leads: @leads %>
        </div>
    </div>
</div>

app/views/leads/new.html.erb
<%= render "leads/form", lead: @lead %>