config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'leads#index'
  resource :leads
  resource :customers

  get '/dashboard', to: 'application#dashboard'
  post '/leads/update/status', to: 'leads#update_status_complete', as: 'lead_update_status'
  post '/lead_generation', to: 'leads#lead_generation'
  get '/leads/generate', to: 'application#export', as: 'lead_generate_csv'
  get '/leads/generate_lead_data', to: 'application#export_lead_data'
  get '/website_leads', to: 'leads#website_leads', as: 'website_leads'
  post '/update/assigned_to', to: 'leads#update_assigned_to', as: 'update_assigned_to'
  get 'search/tickets', to: 'leads#find'
  post 'search/tickets', to: 'leads#find_filter'
  get 'customers/index', to: 'customers#index'
  get 'customers/fetch', to: 'customers#fetch_customer'
  delete 'customers/delete', to: 'customers#destroy', as: 'customers_destroy'
  post 'customers/merge', to: 'customers#merge_customers'
  get '/customers/generate_customer_items_data', to: 'customers#export_customer_order_data'
  get '/work/index', to: 'application#work_index'
  post 'customers/called', to: 'customers#called'

  # authentication
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'
end

app/models/customer.rb
class Customer < ApplicationRecord
    has_many :leads, dependent: :destroy
    has_rich_text :note

    scope :last_month, lambda {
        previous_month_begin = (Time.now - 1.month).beginning_of_month
        previous_month_end = (Time.now - 1.month).end_of_month
        where('created_at BETWEEN ? and ?',previous_month_begin,previous_month_end)
    }

    scope :for_month, -> (specific_month) {
        specific_month_begin = (Date.parse(specific_month)).beginning_of_month
        specific_month_end = (Date.parse(specific_month)).end_of_month
        where('created_at BETWEEN ? and ?',specific_month_begin,specific_month_end)
    }

    def self.to_csv
		attributes = %w{id customer_info items}
		
		CSV.generate(headers: true) do |csv|
			csv << attributes
	
			all.find_each do |user|
			csv << attributes.map{ |attr| user.send(attr) }
			end
		end
	end

    def customer_info
		master_string = ""
        master_string += "#{company_name} |" if company_name.present?
        master_string += "#{name} |" if name.present?
        master_string += "#{mobile} |" if mobile.present?
        master_string += "#{email}" if email.present?
        master_string
	end

    def items
        Lead.where(customer_id: id).pluck(:item_type).compact.map{|arr| JSON.parse(arr).reject(&:blank?)}.flatten.uniq.join(",")
    end

    def self.merge_customers_logic(customer_ids)
        primary_customer = Customer.find_by(id: customer_ids.first)
        secondary_customer_ids = customer_ids - [primary_customer.id.to_s]
        ActiveRecord::Base.transaction do
            secondary_customer_ids.each do |customer_id|
                customer = Customer.find_by(id: customer_id)
                customer_leads = customer.leads rescue []
                customer_leads.each do |lead|
                    lead.update(customer_id: primary_customer.id)
                end
                additional_info = primary_customer.note.to_s + "\nMerged #{customer.id} - #{customer.customer_info}"
                result = primary_customer.update(note: additional_info)
                customer.destroy!
            end
        end
    end
end

app/controllers/customers_controller.rb
# frozen_string_literal: true

class CustomersController < ApplicationController
  def index
    @customer = nil
  end

  def fetch_customer
    @customer = Customer.find_by(id: params[:customer_id])

    respond_to(&:html)
  end

  def new
    @customer = Customer.new
  end

  def edit
    @customer = Customer.find_by(id: params[:id])
  end

  def show
    @customer = Customer.find_by(id: params[:id])
  end

  def create
    @customer = Customer.new(customer_params)
    if @customer.save
      if params['customer']['remote'] == 'true'
        render json: @customer
      else
        redirect_to customers_path(id: @customer)
      end
    elsif params['customer']['remote'] == true
      render json: { error: 'Record not saved!' }
    else
      render 'new'
    end
  end

  def update
    @customer = Customer.find_by(id: params[:id])
    if @customer.update(customer_params)
      redirect_to customers_path(id: @customer)
    else
      render 'edit'
    end
  end

  def destroy
    @customer = Customer.find_by(id: params[:id])
    @customer.destroy if @current_employee.email == 'hemanshu@rainbow.com'
    # Do some toast message implementation here
    redirect_to '/customers/index'
  end

  def export_customer_order_data
    @records = Customer.all

    respond_to do |format|
      format.csv { send_data @records.to_csv, filename: 'customer-data-new.csv' }
    end
  end

  def merge_customers
    valid_customers = merge_params['customers'].reject(&:blank?)
    Customer.merge_customers_logic(valid_customers)
    redirect_to '/customers/index'
  end

  def called
    @customer = Customer.find_by(id: params[:id])
    new_note = @customer.note+"\nCalled at #{DateTime.now}"
    @customer.update(note: new_note)
  end

  private

  def customer_params
    params.require(:customer).permit(:name, :company_name, :mobile, :email, :note)
  end

  def merge_params
    params.permit(customers: [])
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<% popup = popup.present? %>
<div class="customer-form">
    <!-- <div class="back-button">
        <a href="<%= (@customer.present? and @customer.id.present?) ? customers_path(id: @customer) : '/admin_dashboard' rescue '/admin_dashboard' %>">
            <i><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-left" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z"/>
            </svg>
            Back</i>
        </a>
    </div> -->
    <%= form_with model: @customer, url: customers_path(id: @customer), id: 'cusomer-form-id' do |form| %>
    <div class="row">
        <div class="col-lg-6">
            <div class='lead-form-input' style="margin-bottom: 20px;">
                <%= form.label :name, "Name" %>
                <%= form.text_field :name, class: 'form-control lead-form-input-style' %>
            </div>

            <div class='lead-form-input' style="margin-bottom: 20px;">
                <%= form.label :mobile, "Mobile" %>
                <%= form.text_field :mobile, class: 'form-control lead-form-input-style' %>
            </div>
        </div>

        <div class="col-lg-6">
            <div class='lead-form-input' style="margin-bottom: 20px;">
                <%= form.label :company_name, "Company Name" %>
                <%= form.text_field :company_name, class: 'form-control lead-form-input-style' %>
            </div>

            <div class='lead-form-input' style="margin-bottom: 20px;">
                <%= form.label :email, "Email ID" %>
                <%= form.text_field :email, class: 'form-control lead-form-input-style' %>
            </div>
        </div>
    </div>

    <div class='lead-form-input' style="margin-bottom: 20px;">
        <%= form.label :note, "Note" %>
        <%= form.rich_text_area :note, class: 'form-control' %>
    </div>

    <% unless popup %>
        <div class='lead-form-input' style="text-align: right;">
            <span class="btn btn-warning"><a href="/customers/index">Cancel</a></span>
            <%= form.submit "Submit", class: 'btn btn-success' %>
        </div>
    <% end %>
<% end %>
</div>

app/views/customers/_show.html.erb
<div class="cutomer-info">
    <div class="flexer-space-between padding-bottom-2">
        <div class="padding-right-2">
            <div class="lead-dull">Name</div>
            <div class="lead-text"><%= @customer.name == "" or @customer.name == nil ? "-" : @customer.name %></div>
        </div>
        <div class="padding-right-2">
            <div class="lead-dull">Comapnay Name</div>
            <div class="lead-text"><%= @customer.company_name == "" or @customer.company_name == nil ? "-" : @customer.company_name %></div>
        </div>
        <div class="padding-right-2">
            <div class="lead-dull">Mobile</div>
            <div class="lead-text"><%= @customer.mobile == "" or @customer.mobile == nil ? "-" : @customer.mobile %></div>
        </div>
        <div class="padding-right-2">
            <div class="lead-dull">Email ID</div>
            <div class="lead-text"><%= @customer.email == "" or @customer.email == nil  ? "-" : @customer.email %></div>
        </div>
        <div class="padding-right-2">
            <div class="lead-dull">GST Number</div>
            <div class="lead-text"><%= @customer.gst_number == "" or @customer.gst_number == nil ? "-" : @customer.gst_number %></div>
        </div>
    </div>
    <div>
        <div class="lead-dull">Note</div>
        <div class="lead-text"><%= @customer.note %></div>
    </div>
</div>

<div class="button-div">
    <span class="btn btn-warning"><a href="<%= edit_customers_path(id: @customer) %>">Edit</a></span>
    <span class="btn btn-success"><a method="POST" href="/customers/called?id=#{@customer.id}">Called</a></span>
    <span class="btn btn-danger"><a href="<%= customers_destroy_path(id: @customer) %>" data-method="delete" data-confirm="Are you sure ?">Delete</a></span>
</div> 

app/views/customers/edit.html.erb
<%= render 'customers/form', customer: @customer %>

app/views/customers/fetch_customer.html.erb
<div class="customer-index">
    <%= render "customers/show", customer: @customer if @customer.present? %>
</div>

app/views/customers/index.html.erb
<div class="customer-index">
    <div>
        <h2>Add User Button</h2>
        <a href="<%= new_customers_path %>"><button class="btn btn-warning">Add New</button></a>
    </div>
    <div class="pt-5">
        <h2>Search User Form</h2>
        <%= form_with url: '/customers/fetch', method: :get do |form| %>
            <%= form.select :customer_id, customer_select, {}, {id: 'customer_select_2', class: 'form-control lead-form-input-style', required: true} %>
            <button class="btn btn-success" type="submit">Search</button>
        <% end %>
    </div>
    <% if @current_employee&.email == "hemanshu@rainbow.com" %>
        <div class="pt-5">
            <h2>Merge Users Form</h2>
            <%= form_with url: '/customers/merge' do |form| %>
                <%= form.select :customers, customer_select, {}, {id: 'customer_select_2_for_merge', class: 'form-control lead-form-input-style', required: true, multiple: true} %>
                <%= form.submit "Merge", class: 'btn btn-success', :data => {:confirm => 'Are you sure?'} %>
            <% end %>
        </div>
        <div class="pt-5">
            <h2>Download Customer Order Data</h2>
            <a href="/customers/generate_customer_items_data.csv">
                <button type="button" class="btn btn-success">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-save" viewBox="0 0 16 16">
                        <path d="M2 1a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H9.5a1 1 0 0 0-1 1v7.293l2.646-2.647a.5.5 0 0 1 .708.708l-3.5 3.5a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L7.5 9.293V2a2 2 0 0 1 2-2H14a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h2.5a.5.5 0 0 1 0 1H2z"/>
                    </svg> Export
                </button>
            </a>
        </div>
    <% end %>
</div>

<div class="modal fade" id="customerShowModal" tabindex="-1" aria-labelledby="customerForm" aria-hidden="true">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="customerFormModalLabel">New Customer</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <%= render "customers/show", customer: @customer if @customer.present? %>
        </div>
        <div class="modal-footer">
            <span class="edit-button cursor-pointer" id="customer-close" data-bs-dismiss="modal">Close</span>
            <button type="button" class="btn btn-warning" id="popup-customer-submit">Save</button>
        </div>
        </div>
    </div>
</div>

app/views/customers/new.html.erb
<%= render 'customers/form', customer: @customer %>

app/views/customers/show.html.erb
<div class="customer-show">
    <%= render "customers/show", customer: @customer %>   
</div>