config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'leads#index'
  resource :leads
  resource :customers

  get '/dashboard', to: 'application#dashboard'
  post '/leads/update/status', to: 'leads#update_status_complete', as: 'lead_update_status'
  post '/lead_generation', to: 'leads#lead_generation'
  get '/leads/generate', to: 'application#export', as: 'lead_generate_csv'
  get '/leads/generate_lead_data', to: 'application#export_lead_data'
  get '/website_leads', to: 'leads#website_leads', as: 'website_leads'
  post '/update/assigned_to', to: 'leads#update_assigned_to', as: 'update_assigned_to'
  get 'search/tickets', to: 'leads#find'
  post 'search/tickets', to: 'leads#find_filter'
  get 'customers/index', to: 'customers#index'
  get 'customers/fetch', to: 'customers#fetch_customer'
  delete 'customers/delete', to: 'customers#destroy', as: 'customers_destroy'
  post 'customers/merge', to: 'customers#merge_customers'
  get '/customers/generate_customer_items_data', to: 'customers#export_customer_order_data'
  get '/work/index', to: 'application#work_index'
  post 'customers/called', to: 'customers#called'

  # authentication
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RainbowCRM</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'ajax_calls', 'data-turbolinks-track': 'reload' %>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
  </head>

  <body>
    <section class="main">
      <!-- Side navbar -->
      <div class="sidebar">
        <div class="brand">
          <%= image_tag "logo.png" %>
        </div>
        <ul>
          <li><a href="<%= root_path %>">
            <div>
              <span><%= image_tag "home.png" %></span>Home
            </div>
          </a></li>
          <li><a href="<%= website_leads_path %>">
            <span><%= image_tag "overview.png" %></span>Website Leads<span class="badge" style="background: white;color: maroon;margin-left: 5px"><%= website_orders_count %></span>
          </a></li>
          <li><a href="<%= new_leads_path %>">
            <span><%= image_tag "insights.png" %></span>Create Order
          </a></li>
          <li><a href="/search/tickets">
            <span><%= image_tag "overview.png" %></span>Search Record
          </a></li>
          <li><a href="/customers/index">
            <span><%= image_tag "overview.png" %></span>Customer Actions
          </a></li>
          <li><a href="/dashboard">
            <span><%= image_tag "overview.png" %></span>Dashboard
          </a></li>
          <% if @current_employee&.email == "hemanshu@rainbow.com" %>
            <li><a href="/work/index">
              <span><%= image_tag "overview.png" %></span>Work Index
            </a></li>
          <% end %>
        </ul>
      </div>
      
      <!-- Container -->
      <div class="main-inner">
        <!-- navbar -->
        <nav>
          <% if @current_employee.present? %>
            <form class="form-style" action="<%= root_path %>">
              <input class="form-control" type="search" name="query" value="<%= params[:query] %>" placeholder="Search" aria-label="Search">
              <button class="btn btn-success my-2 my-sm-0" type="submit">Search</button>
            </form>
            <div class="profile-info">
              <%= link_to '/logout', method: :post, :data => {:confirm => 'Are you sure?'} do %>
                <%= image_tag "shutdown.png" %>
              <% end %>
            </div>
          <% end %>
        </nav>

        <!-- Main content -->
        <div class="main-content">
          <%= yield %>
        </div>
      </div>
    </section>

    
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script>
      $('#customer_select_2').select2({
          width: "80%",
          placeholder: 'Search for customer',
          minimumInputLength: -1
      });
      $('#customer_select_2_for_merge').select2({
          width: "80%",
          placeholder: 'Search for customer',
          minimumInputLength: -1
      });
      $('#customer_select_2_2').select2({
          width: "250px",
          placeholder: 'Search for customer',
          minimumInputLength: -1
      });
      $('#item_select_2').select2({
          width: "80%",
          placeholder: 'Search for Item',
          minimumInputLength: -1, 
      });
      $('#popup-customer-submit').on('click', function(){
        var form = $("#cusomer-form-id");
        var data = {"customer": {}}
        $.each(form.serializeArray(), function(i, field) {
            data["customer"][field.name] = field.value;
        });
        data["customer"]["remote"] = true;
        $('#customer-close').click();
        if (true) {
          $.ajax({
            url: "/customers",
            type: "POST",
            beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
            data: data,
            success: function(data){
                console.log(data);
                var option = {
                  id: data.id,
                  name: data.name + '-' + data.company_name,
                }
                var newOption = new Option(option.name, option.id, true, true);
                $('#customer_select_2').append(newOption).trigger('change');
            },
            error: function(){
              console.log("AJAX call unsuccesful");
            }
          });
        }
        else{
          alert("The form has errors, couldn't be submitted");
        }
      });

      $('#popup-new-item-submit').on('click', function(){
        var new_item = $("#new_item_string").val();
        $('#item-close').click();
        $("#new_item_string").val('');
        var option = {
          id: new_item,
          name: new_item,
        }
        var newOption = new Option(option.name, option.id, true, true);
        $('#item_select_2').append(newOption).trigger('change');
      });

      $('#show-status-update').on('change', function(){
        $('.status-icons-div').css('display','flex');
      });

      $('#assigned-to-update').on('change', function(){
        $('.assigned-to-icons-div').css('display','flex');
      });

      $('.lead-status-style .bootstrap-close-icon').on('click', function(){
        var data = $('.lead-status-style').data('current_lead');
        $('.status-icons-div').css('display','none');
        $('#show-status-update').val(data);
      });

      $('.assigned-to-close-icon').on('click', function(){
        $('.assigned-to-icons-div').css('display','none');
      });

      $('.lead-status-style .bootstrap-check-icon').on('click', function(){
        var state_data = $('#show-status-update').val();
        var lead_id = $('#lead-id').data("lead_id");
        $.ajax({
          url: "/leads/update/status",
          type: "POST",
          beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
          data: {id: lead_id, status: state_data},
          success: function(data){
              alert(data.success);
              $('#show-status-area').text(state_data);
              $('.status-icons-div').css('display','none');
          },
          error: function(){
            console.log("AJAX call unsuccesful");
          }
        });
      });

      $('#calendar-icon-toggle').on('click', function(){
        $('#calendar-icon-toggle').css('display','none');
        $('#date-picker-flow').css('display','block');
      });
    </script>
  </body>
</html>